### ISSUE TITLE
Multiple Invoices can be created

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#100]
Build: MASTER 2016.5.30
Version: BES V16.0 Fix 4+
Test category: creative Test

[Steps to reproduce]
1. Login marketplace as customer;
2. Click on "ACCOUNT->Payment";
3. Click on the pen icon of payment type, modify the Display as from "Invoice" to "test1", and then click on "Save" button;
4. Login as administrator to blue portal, set "HIDE_PAYMENT_INFORMATION" to true;
5. Login marketplace as customer, select a service not free of charge to make a subscription;
6. Login as administrator to blue portal, set "HIDE_PAYMENT_INFORMATION" to false;
7. Login marketplace as customer, click on "ACCOUNT->Payment";
8. Now you see "Invoice" and "test1", Repeat the step 3.

[Expected result]
In Step 8, I don't expect a new "Invoice". The default used should be test 1 for the subscription created. So it is not necessary in my opinion to create a "new" Invoice, just because the display name is different.
Otherwise, in step 8, some error message should be shown because the "test1" has already exists.
Also, if it is possible to create multiple invoices,  it should then be possible to delete multiple invoices.

[Observed result] 
In step 8, no additional invoice is shown. 

[Details]
See screenshot of multiple Invoices
![multipleinvoices](https://cloud.githubusercontent.com/assets/15086024/15648329/13d0bef8-266a-11e6-8813-fff74d0d3571.png)

**Comment by GoebelL** [comment]
I guess this is a longer existing issue and not related to HIDE_PAYMENT_INFORMATION. 
Please note that the display name is the identifier. I don't see any reason why this should be changeable for invoice. In my opinion, step 3 should be disallowed to avoid having multiple payment types with INVOICE. 
The customer can have different payment types, which are directly charged by payment runs, such as credit cards, debit accounts or whatever. But there is only one type INVOICE, as alternative to directly changed. Multiple INVOICE instances do not add any value and therefore do no make sense for me. 
However this might be not so easy, considering that DB migration will be required now to clean and replace the redundant invoice types in existing DBs.

Since there is no further user impact, I consider this issue as improvement request with low priority. 
@mdehn 
Do you agree with me?

**Comment by mdehn** [comment]
Multiple INVOICE payment types do not make any sense. Migration of existing DBs is low priority.

**Comment by SylviaDehn** [comment]
This is only possible due to hide payment types. This creates a "new invoice", instead of reusing the existing one. Why now allow renaming "INVOICE"? This would be a level down.

**Comment by GoebelL** [comment]
This should be solved with [issue#101]. Making HIDE_PAYMENT_INFORMATION read-only, this use case will no longer exist.
