### ISSUE TITLE
The payment page can be opened with the URL access when the HIDE_PAYMENT_INFORMATION is true.

### ISSUE THREAD

**Issue by jiangweiyi** [servicecatalog/development#119]
#Date: 2016/06/02
[Test category]: creative Test

[Steps to reproduce]
1. Set the HIDE_PAYMENT_INFORMATION as true in configsetting.properties file.
2. Install CTMG.
3. Login as customer, go to "account" page.
4. Input the URL as http://g08fnstd131528.g08.fujitsu.local:8080/oscm-portal/marketplace/account/payments.jsf

[Expected result]
After step3, there is no entry for payment.
After step4, the payment page cannot be opened and should be some warning message.

[Observed result]
After step3, there is no entry for payment.
After step4, the payment page can be opened and can do some modification or delete operations.

**Comment by GoebelL** [comment]
The page is to be hidden if HIDE_PAYMENT_INFORMATION is set. This is, because it doesn't make sense to offer functionality to the customers for creating payments, if they cannot use such due this configuration. On the other hand, it doesn't cause any harm and there is neither an authority violation nor information leak this the payment page is for customer access. 

Please fix. Return a blank body page showing respective message in the error panel.

**Comment by redmond2683** [comment]
Fixed in 08f368a
