### ISSUE TITLE
The suspended subscriptions displayed incorrectly

### ISSUE THREAD

**Issue by wangyingfnst** [servicecatalog/development#124]
Date: 2016/06/02
[Test category]: creative Test
Severity：Minor

[Steps to reproduce]
1. Login in marketplace as customer;
2. Click on "ACCOUNT->Processes->Add Process Trigger";
3. Fill the following fields "Display as", Type="Subscribe to service" Target type="Web Service", Target URL="http://mockproductServer:port/oscm-integrationtests-mockproduct/NotificationService?wsdl",
check the "Suspends the execution of the process", then click on "Save" button;
4. Click on "HOME->Show Details->Get it now" to make a subscription;
5. Click on "ACCOUNT->Subscriptions" to check the subscription created just now.

[Expected result]
In step 5, the subscription created just now should be listed in the "Available to administrate", and when click the administrate icon, the "Terminate" button should be clicked successfully.

[Observed result]
In step 5, the subscription created just now was not listed in the "Available to administrate", but listed in the "Waiting for reply", and no button can be clicked to terminate the subscription. In addition, the displayed contents of suspended subscriptions were not tidy and clear.
![the suspended subscriptions displayed incorrectly](https://cloud.githubusercontent.com/assets/14818896/15889644/8d24cd40-2d9e-11e6-9a5b-da0469995fa3.png)

**Comment by StavrevaS** [comment]
The expectation is wrong. The subscriptions are not created yet because of suspending trigger and cannot be administrated or terminated. If the user do not want to create this subscription, he can abort the process (Process menu). 
The names are too long and displayed with breaks which is also expected behavior.
It works as designed, so I will set the issue to invalid.
