### ISSUE TITLE
status of subscription NOK

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#164]
Date:2016/06/29

[Steps to reproduce]
1. As marketplace owner, choose "Marketplace/Manage access", define "Authorized customers only"
2. Unclick an organization that has a subscription that was published to this marketplace
3. This results in a warning stating that there is at least one subscription that will be suspended. 
    Press ok.
4. As customer (that has another marketplace where he can still login), login to another marketplace
5. Look at status of subscrptions that were on restricted access marketplace

[Expected result]
status: suspended (as stated in RQ)
(even though I do not think it should be possible to unclick the organization that has active subscriptions)

[Observed result]
status: suspended, update payment types.

[Details]
This is confusing because normally subscriptions only become suspended if payment types are missing. If I now update payment types, then I can reactivate subscription. Do we want this?
Of course this is only possible if the customer has the possibility to login to another marketplace,
and if "HIDE_PAYMENT_TYPES" is not set to true. 

As suggested by Lorenz, it may be better to not allow restricting access to organizations that have active subscriptions on the marketplace. (org cannot be unclicked). These customers should terminate their subscriptions, before this is possible.

**Comment by GoebelL** [comment]
With current design, active subscriptions will be suspended when restricting the customer access to the marketplaces where they are hosted. This is first of all, to prevent in any case, that customers are continued to be be charged for subscriptions they can't access anymore. 

However, after all, we concluded that suspending the customer subscription is not the appropriate measure to achieve this. Despite of the here mentioned interference with the payment type handling, there is deeper concept lack, concerning the question of how to resume them in this use case.

Idea: KISS. If the marketplace manger attempts to remove access for a customer C to a marketplace M:
* if C doesn't have any active subscriptions on M, the operation succeeds and C cannot access M anymore 
* if C has active subscriptions on M, the operation fails with a respective error message and access to M remains for C.

@mdehn 
Would this be an accepted solution for you?

**Comment by mdehn** [comment]
yes, that is ok.

**Comment by GoebelL** [comment]
As just discussed, there is an easier solution.

Currently, when the marketplace owner selects to provide access to his marketplace for authorized customers only, he gets the list of all customers, where those customers are preselected, who have at least one active subscription on that marketplace. This is already implemented.

Proposed Enhancement: Access cannot be removed for customers with active subscriptions on the selected marketplace. The check-boxes for those customers will be disabled in the list.
 If such customers with active subscriptions exist, a respective note will be displayed on the manage access page, that the access cannot be removed for these customers, because they have active subscriptions. These subscriptions have to be terminated first.

Developers have to take care with the "select all" function in this table, in order that these disabled check-boxes are excluded for the "all" checkbox handling.

**Comment by SuessI** [comment]
Adapted the documentation (en/de) for this proposal. Will be included in next doc build (>2016-07-13)

**Comment by jiangweiyi** [comment]
Verified by FNST
[Verified-build] BES_MASTER_DELIVERY-744 2016/07/22
[Verified-details]The customer with active subscription cannot be disable from a marketplace, so verified.
