### ISSUE TITLE
vmware controller: resource-extention.xml is removed after setting up glassfish for VMware adapter

### ISSUE THREAD

**Issue by misako0927** [servicecatalog/development#170]
[Frequency]
Always

[How to reproduce]

1. Setting up the Application Server Resources with this command:

  ```
  <ANT_HOME>/bin/ant -f build-glassfish.xml SETUP
  ```

[Expected result]
resource-extention.xml is not removed

[Observed result]
resource-extention.xml is removed

User cannot resetup the application server because of this issue.

**Comment by StavrevaS** [comment]
This issue is fixed with fixing issue #169.
The file resources-extenstion.xml is generated during the installation process and deleted afterwards. But the template resources-extension-template.xml which is a base for the resources-extension.xml will not be deleted. So the installation package will stay unchanged.

**Comment by StavrevaS** [comment]
The bug is fixed with fixing

**Comment by SylviaDehn** [comment]
verified for new installation; update installation does not remove file 2016/07/22
