### ISSUE TITLE
imq.brokerid incorrect after installation of master indexer domain

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#248]
[Build] 2016/07/25
1. specify imq.brokerid=XXX in 
   <installationDir>\domains\indexer_domain\glassfishJMSBroker.properties
2. after installation check
   <glassfish installdir>\glassfish\domains\master-indexer\imq\instances\imqbroker\props\config.properties

[Expected result]
imq.brokerid=XXX

[Observed result]
imq.brokerid=broker1

**Comment by SylviaDehn** [comment]
Please take care of this problem; it is important

**Comment by StavrevaS** [comment]
We have a validation query imq.persist.jdbc.connection.validationQuery=SELECT 1 FROM mqbkr41sbrokerid_masterindexer on the master indexer broker table. This means the indexer broker name should not be changed, it should be brokerid_masterindexer, because the table names contain the broker id.
For the bes domain, the broker name could be changed and it works.

The following changes in the glassfishJMSBroker.properties files of both domains may give some more explanation to the user:

- Rename the default brokerid  for master inedexer to the real value given by the installation - brokerid_masterindexer.
- Comment this property and the validation queries properties that they should not be changed.

**Comment by StavrevaS** [comment]
@gertipoppel please adapt installation guide as follows:

Page 39:
Note: If you are using OSCM in a multi-node installation, make sure to change the default setting 
imq.brokerig to a value that is unique for every node, except for master indexer domain.

**Comment by SuessI** [comment]
Changed the sentence as follows:

Note: If you are using OSCM in a multi-node installation, make sure to change the default value of the imq.brokerid setting to a unique value for the bes-domain on every slave node. Do **not** change the setting in the master indexer domain.

**Comment by SylviaDehn** [comment]
[Version] 2017/02/17 verified installation and documentation
