### ISSUE TITLE
The help icon on the login failed page can not be used.

### ISSUE THREAD

**Issue by jiangweiyi** [servicecatalog/development#265]
Date: 2016/07/22
[Test category]: creative Test

Severity: minor

[Steps to reproduce]
1. Marketplace owner create a "closed" marketplace;
2. Then do not select a customer to grant the access;
3. Go to the homepage of this marketplace;
4. Login as this customer. 

[Expected result]
Login failed.

[Observed result]
With SAML_SP mdoe, there is the error message "Login failed. You have no access to this marketplace. ", the help button "?" can be clicked, but do not display a help page after clicked.

**Comment by StavrevaS** [comment]
@grubskim, please consider this by fixing #194

**Comment by grubskim** [comment]
Caused by missing help pages for the new error messages:
1) ex_AccessToClosedMarketplaceException.htm - error message "You do not have access to this marketplace. "
2) ex_LoginToClosedMarketplaceException.htm - error message "Login failed. You do not have access to this marketplace. "

/oscm-portal-help/help/en/help/tasks/ex_AccessToClosedMarketplaceException.htm
/oscm-portal-help/help/en/help/tasks/ex_LoginToClosedMarketplaceException.htm

**Comment by SuessI** [comment]
Please rename the keys to access the help pages to the following: 

error_access_closed_marketplace.htm
error_login_closed_marketplace.htm

I will add these pages to master in en/de/jp.

**Comment by SuessI** [comment]
Required help pages are now available in master branch. Names agreed with Michal are now:
-   error_loginToClosedMarketplace.htm
-   error_accessToClosedMarketplace.htm

**Comment by SuessI** [comment]
Remaining issues in code are solved in #194

**Comment by SylviaDehn** [comment]
[Build]2016/08/09 verified
