### ISSUE TITLE
 [PT]The value of Connection properties is deleted

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#287]
[Summary]
The value of Connection properties is deleted. 

[Product name and version]
V16.1 GA1

[Client IDE]
OS      : Windows10
Browser : Edge(25.10586.0.0)

[Reproduce frequency]
always

[Bug Classification]
Short Name:PB-InvFun
Fundamental Function:No
Workaround:Yes
Severity:Minor

[How to reproduce]
1.Open the "Manage billing system".
2.Click "Add".
3."Billing system ID" is input.
4.Click "+" button four times.
5.The property value is input.
6.Click "-" button of top field.

[Expected result]
Clicked "-" button line is deleted.

[Observed result]
Clicked "-" button line is deleted. 
And the value of other lines is deleted.

[Detail]
Clicked "-" button line is deleted and value of other lines is deleted.
An unrelated value should not be deleted.

[Message and logs]
nothing

**Comment by SylviaDehn** [comment]
[Build] 2016/08/18 verified FF, Edge, Chrome, IE11

**Comment by DawidCh** [comment]
The compare method on ConnectionProperty has been written with not all cases taken into consideration. Because of that identification of row, which has been removed, did not worked properly while removing object from tree collection. Proxy mechanism has been implemented to care about uniqueness and proper removal and addition of the rows.
