### ISSUE TITLE
VMware Controller: SSL is disabled in Script.java

### ISSUE THREAD

**Issue by misako0927** [servicecatalog/development#292]
In the Script.java of VMware controller, there are SSL disable method.
It looks bad in security point of view.
Please investigate this method and fix if needed.

https://github.com/servicecatalog/development/blob/master/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/Script.java

~~~
    private class TrustAllTrustManager implements javax.net.ssl.TrustManager,
            javax.net.ssl.X509TrustManager {
...
   }
    public Script(VMPropertyHandler ph, OS os) throws Exception {
...
        // TODO load certificate from vSphere host and install somehow
        disableSSL();
    }
    void disableSSL() throws Exception {
        javax.net.ssl.HostnameVerifier verifier = new HostnameVerifier() {
...
    }
~~~

**Comment by StavrevaS** [comment]
There are 2 steps where controller is involved working with the script:
1. The controller downloads the script from the specified URL in the service configuration
2. The controller uploads the script to the provisioned VM in vSphere.

Analysis and solution approach for 1

The download URL can be specified by technology provider/supplier. Normally it is the same organization with the 2 roles.  This organization is trusted by platform operator, it registers the technology providers and suppliers. In this case, it is ok to have download URL with http. Even if the passwords or some other sensible information is written, the target where the script will be executed is not known for a man in the middle. Furthermore, the https can be activated, but the controller does not verify certificates.
The customer has no need to create scripts by provisioning, he has access to the VM and can configure the VM after he gains access to it.
So it does not make a sense for supplier to make a script parameters (URL and user credentions for executing the script) user options. The user should not be able to see or change this parameters. Only supplier may need the script, if he wants to do some initial configuration on the provisioned VM. The scripts depend on the target template (Windows, Linux variants).

It should be maybe documented as restriction to avoid making the script available for configuring by subscribing. However, the supplier must carefully select the parameters configurable by subscribing, so he will probably not set the script URL as user option. Otherwise he cannot control the provisioning process. If something goes wrong the supplier would not have access to the scripts defined by customer. 

If https communication is required, the technology provider/supplier, must be able to import certificates into app domain where the controller is deployed and validate by SSL handshake.
 
Analysis for 2:

The problem with uploading the script to the provisioned machine is that we do not have a solution how to deal with the https upload URL returned by vSphere system. The relationship between VMware controller and vSphere is already trusted because of API calls (certifaicate is imported in the app domain). But in this case the connection is done with the provisioned VM (with own host name), not the host name from vSphere system and the installed certificate doe not help.

**Comment by misako0927** [comment]
I understand step 2 only use http. We have no way to get https URL from vSphere SDK.
SSL disable method only affect to step 1.
Is my understanding correct?

**Comment by StavrevaS** [comment]
No. In step 2, the returned URL by vSphere is https. But this is URL to the newly provisioned machine. It is still not known how to deal with this situation, since the certificates of the new host must be available.

**Comment by misako0927** [comment]
I got it.
I understand step 1 can be fixed some how but step 2 have no way to fix for now.
These will be restrictions for v16.1. But about step 1, it should be fixed in future release.

**Comment by GoebelL** [comment]
Please add a note in VMware vSphere Integration Guide that the script parameters are internal and must not be defined must not be defined as user option for the customer.

**Comment by gertipoppel** [comment]
Done. I have added the following to the VMware vSphere Integration Guide: 
"For security reasons, the SCRIPT_URL parameter must not be configurable by the user subscribing to the service."
