### ISSUE TITLE
Dropdownlists are unsorted

### ISSUE THREAD

**Issue by uspecht** [servicecatalog/development#304]
It is difficult to find items in drop down lists. 
![dropdownlist](https://cloud.githubusercontent.com/assets/17145235/17882649/fe14972e-690d-11e6-8b4d-703e1d054cc0.jpg)
Therefor it should be improved by sorting lists alphabetically.

**Comment by angarg12** [comment]
This issue cannot be solved at the storage layer.

Some of the drop down lists are built as an aggregation of different data sources. That means that even if the original sources are sorted, their aggregation won't be.

Therefore the solution consist on sorting the results as close as the presentation layer as possible.

**Comment by angarg12** [comment]
Currently the UI beans sometimes return a sorted and sometimes an unsorted list (e.g. ReportBean).

In order to provide consistently sorted drop down menus, we should homogenize the treatment of lists.

This behaviour can be achieved either by sorting the data at the end of each Bean call, or client side using Javascript. On [this post](http://stackoverflow.com/questions/27443227/how-to-sort-a-list-that-will-be-localized-in-jsf-output) there is a sample code on how to do this.

What approach to use is an architectural decision that should consider performance impact and implementation effort of each solution.

**Comment by GoebelL** [comment]
I consider the approach with client side sorting best suitable in terms of efforts and risk of side effects. 

Please contribute the Javascript handler to admUtils.js, but take care of preserving the OSCM layout customization, when using the styleClass attribute as demonstrated in the mentioned sample.

**Comment by angarg12** [comment]
I've created a pull request and will link the issue there

#312

**Comment by GoebelL** [comment]
This will be integrated for next release after all tests have passed successfully.

**Comment by DawidCh** [comment]
Merged
