### ISSUE TITLE
Provide K5 Controller as Product Component

### ISSUE THREAD

**Issue by mdehn** [servicecatalog/development#322]
Support the provisioning of K5 IaaS services.

**Comment by StavrevaS** [comment]
K5 supports OpenStack, so we can use the OSCM OpenStack controller as a base.
OpenStack controller comes with a Heat CFN (AWS CloudFormation) compatible template in json and yaml format. 
However OpenStack support also HOT templates (also Heat, but native and not CFN backward-compatible), typically given in yaml format.

1. What is the requirement for K5 Cloud, which kind of templates should be supported:
- Heat CFN compatible;
- HOT - Heat native; 
2. Which template format should be used:
- json;
- yaml;
- both?

**Comment by StavrevaS** [comment]
Which version of OpenStack is used by K5 Cloud?

**Comment by misako0927** [comment]
K5 supports only HOT template(version 2013-05-23) in yaml format.

**Comment by misako0927** [comment]
K5 Cloud use IceHouse version of OpenStack.

**Comment by StavrevaS** [comment]
Most, if not all operations can be covered with the OpenStack Orchestration (Heat) and Compute (Nova) API. 

1. Provisioning of VMs in the K5 Cloud:

Provision one or more **VMs (servers)** in one request. This can be done by both APIs. We already support provisioning a stack with one server using the Heat API. Only Heat API supports HOT templates. The **tenant (project)** and **region** will be specified for the Keystone API by the authentication, in order to get the right service endpoints (Heat and Nova). The **availability zone** and **networks** can be specified in the HOT template by describing the VM (server) resource.

**Comment by StavrevaS** [comment]
Important topic may be tagging of the resources.  OpenStack can tag any kind of a resource using Networking API. 
- Tag any resource - Networking API
- Tag stack - Heat API
- Tag server - Nova API
Since the OpenStack allows tagging in different levels, it is important to know what kind of tags are used in K5 Cloud.  I assume VMs (servers) should be tagged.
