### ISSUE TITLE
Support GlassFish Server 4.1

### ISSUE THREAD

**Issue by mdehn** [servicecatalog/development#336]
The current GlassFish v3.2.2 is outdated and patch support will be stopped in the near future.

**Comment by DawidCh** [comment]
New glassfish has been introduced. Nothing official yet, but we already have beta builds. Instead of migration to glassfish 4.1 I would suggest to migrate to 5.0 directly (http://download.oracle.com/glassfish/5.0/index.html)
@mdehn @GoebelL @bogdanbarzu could you please consider the migration?
If we can't go with 5.0, because of sth I'm not aware of, we should consider payara server (http://www.payara.fish/about). This is glassfish based application server. Fully opensource (as we are) with developer and production support and frequent updates.
FYI: last build of glassfish 4.1.1 has been done Oct 7 2015 which in IT world is ages ago.

**Comment by StavrevaS** [comment]
The glassfish 5.0 is a reference implementation for JavaEE 8, which Oracle has delayed for end of 2017 because of major enhancements. 
So migration to glassfish 5.0 should not be done at this moment.

The idea with Payara is interesting, it should fit better for agile processes, but requires more investigation first. Payara is parallel to glassfish 4.x, so if we migrate to glassfish 4.x, it will be probably easier to do this step afterwards. More time to investigate the implications is necessary. I can think of installation changes for example, the integration tests environment etc.  Existing customers must be also taken into account. How can they migrate? How much effort is needed?

If we want migration in 16.2 release there is no chance to start any other, but glassfish 4.1

**Comment by DawidCh** [comment]
Glassfish 4 is delivered.
