### ISSUE TITLE
Can do an URL-switch between marketplaces: therefore able to see 'forbidden' marketplaces 

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#388]
[Version]
V16.2 

[Date]
2016/10/19

[Test category] 
Creative

[Description]
Create two tenants with marketplace for each (Ta M1 and Tb M2)
User I belongs to Ta
Try to log on to M2: error: Login failed. Check whether the specified user ID or password are correct. 
Remember the marketplaceid: (like :9fe000e4)
clear browser cookies or restart browser
Log on to marketplace where I belongs (M1)
check the url like: https://time.darkside.com:8081/portal/marketplace/?mId=d5b8f512

Now change the url to:
https://time.darkside.com:8081/portal/marketplace/?mId=9fe0004e 
and press enter:
Yippee: I am in the 'forbidden' marketplace. 

[Steps to reproduce]
see above
[Expected result]
Changing in the url the marketplace id should not matter: i cannot change the marketplace, or i get an error: Login failed. Check whether the specified user ID or password are correct. 
[Observed result] 
I can reach an marketplace where i do not belong to.
[Details]
See above; 

[Messages and logs]

Blocker: Due to security breach; multi tenancy broken

**Comment by StavrevaS** [comment]
@AndreasTWolf please check if you are still in the right tenant and organization context for the user, by switching to marketplace from different tenant.
I have discussed this with @GoebelL, and it seems that access to the tenant-specific marketplaces is allowed. If this feature is not wanted, the operator can define the marketplaces as closed and allow access only to customers from marketplace tenant. 

Even before multitenancy, the customer could switch to other marketplaces, which are not assigned to him and subscribe to services offered there. 

OSCM has no marketplace-specific login concept. 

So if the user has still its authentication context (tenant, organization), it is not a security problem, but more a matter of configuration of the platform. The effect is that the customer from one tenant, can subscribe to the services of the other tenant. 

From multitenancy point of view, this maybe not the best solution. Since the platform operator is responsible for managing tenants for now, we can let this as it is for now. The marketplace owner can prevent this situation with defining the marketplace as closed.

A new marketplace-specific login concept requires more analysis and concept work and cannot be treated as bugfix.

**Comment by GoebelL** [comment]
>and it seems that access to the tenant-specific marketplaces is allowed. 
This is correct. All marketplaces are "open to all tenants" by default. We have concrete customer scenarios where this is needed. If it's not, the marketplace owner can explicitly restrict the marketplace access for selected organizations, as you said.

**Comment by StavrevaS** [comment]
@gertipoppel, please document the following. Even if the marketplace can be associated with tenant, it is still open by default for publishing and subscribing services. Per marketplace configuration, the marketplace owner can decide to restrict which sellers can publish their services (marketplace with authorized sellers) and which customers can subscribe (closed marketplace).

**Comment by gertipoppel** [comment]
I have added the following note in the Operator's Guide as well as on the online help topic for "Managing tenants": 

You as the platform operator are responsible for the correct configuration of tenants!
Be aware that although a marketplace can be associated with a tenant, the marketplace is, by default, still open for publishing and subscribing to services. To avoid this, configure the marketplace in a way that you restrict the access to it to specific sellers who can publish their services (authorized sellers only) and to specific customer organizations that can subscribe to services published on the marketplace (closed marketplace). To do so, you need to be the owner of the marketplace.

Modified sources: 
DocSources/en/OperationsGuide/Organizations/c_ManageTenants.xml
DocSources/en/help/tasks/operator_manageTenants.xml


@misako0927 - This is an additional change in the online help. Please translate to Japanese.

**Comment by misako0927** [comment]
I translated to Japanese.
