### ISSUE TITLE
login with tenant id does not work if previously logged in and out of another tenant/IDP in same browser

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#417]
Date: 2016/10/28 16.1 fix2

[Steps to reproduce]
1. IDPs IDP1(used as default), and IDP2 exist, 
2. supplier org is assigned to IDP2 tenant
3. as platform operator log into default tenant IDP:
http://blabla.com:8180/oscm-portal?tenantID=12345678
4. logout as platform operator
5. login as supplier of other tenant with tenant ID
http://blabla.com:8180/oscm-portal?tenantID=bd34f6a8

[Expected result]
get forwarded to IDP of other tenant (corresponding to tenant ID)

[Observed result]
get forwarded to default tenant 

[Details]
The workaround is to delete all cookies. So minor. But given the tenant ID, I do not understand why this is not done correctly.  Here all cookies should be ignored. Plus the existing cookies should be invalidated, right?

**Comment by DawidCh** [comment]
Just answering your doubts. Application is not designed to work with multiple tenants from one browser. It is not real life scenario when user is being logged in using one IDP and just after that he loggs in with different IDP. Tenant is not stored in the cookies, so in my opinion workaround is to kill all the opened sessions (tabs) to oscm.
Nevertheless the bug is duplication of issue #392 and will be fixed soon.
