### ISSUE TITLE
Administration portal UI - hidden UDA values

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#438]
The following values on administration portals must be hidden:

Manage custom attributes:
- default values from custom attributes with "encrypted" flag set to true;

Manage subscription attributes:
- custom attributes with "encrypted" flag set to true

The length of the displayed  password characters (stars/dots) should be fixed.

**Comment by badziakp** [comment]
Details of fix:
- Manage custom attributes: 5 stars are shown in the readonly default value field
- Manage subscription attributes: 5 stars are shown in the readonly value field, input secret is used for editable fields
- Define service/Update service: always 5 stars are shown, passwords can not be seen in the firebug

(technical services issue will be fixed in #439)
