### ISSUE TITLE
Service parameters of type "PWD" not displayed and not editable on UI

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#448]
If a service is defined with parameter of type "PWD", it cannot be displayed or edited on UI
(both, administration and marketplace portal)

**Comment by DawidCh** [comment]
Do I get it correctly? Parameter with type PWD may be only set during importing of technical service and nowhere else?

**Comment by StavrevaS** [comment]
The PWD should in fact replace the old logic with STRING type and suffix "_PWD". But for compatibility reasons both ways would be possible for now to define passwords. I do not say any reason to treat the PWD parameter types differently on UI. So they should be editable, if the technology manager specifies them as configurable.

**Comment by DawidCh** [comment]
Fix has been merged.
TODO: increase coverage on that branch to pull up coverage on master, so issue is not yet closed.

**Comment by DawidCh** [comment]
Coverage have been increased slightly.
[Details of fix]
New jsf component have been added in paramtable.xhtml to displays stars only when field is of type PWD. In addition, when field is being editable content of that field is also masked with 5 stars. Because if that 5 stars cannot be used as password (value of attribute PWD) because it will not be stored in DB.

**Comment by gertipoppel** [comment]
The documentation states that passwords are encrypted and stored in the db. I do not think it is necessary to mention that a password consisting of 5 stars will not be stored (this is very unrealistic). Therefore closing this issue.
