### ISSUE TITLE
encrypted custom attributes shown unencrypted in app log file

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#474]
[Build] 16.1 fix3 25.11.2016
[Steps to reproduce]
1. Turn on logging in log4j.properties for app (ALL)
2. Create aws subscription with custom attributes (level subscription and customer) with encrypted values
3. Check ....\domains\app\logs\server.log

[Expected result]
Encrypted passwords are not shown in clear text

[Observed result]
I can see the passwords in clear text

[Details]
The frame is printed with all attributes:
[#|2016-11-30T15:18:26.779+0100|INFO|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=122;_ThreadName=Thread-2;|---[HTTP request]---
accept: text/xml, multipart/related
cache-control: no-cache
connection: keep-alive
content-length: 3172
content-type: text/xml; charset=utf-8
host: estsdehn.intern.est.fujitsu.com:8881
pragma: no-cache
soapaction: "urn:asyncCreateInstance"
user-agent: Metro/2.2.0-1 (tags/2.2.0u1-7139; 2012-06-02T10:55:19+0000) JAXWS-RI/2.2.6-2 JAXWS/2.2 svn-revision#unknown
<?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">
....
<ns2:attributeId>password id</ns2:attributeId><ns2:encrypted>true</ns2:encrypted><ns2:value>mypassword</ns2:value>
.....
<ns2:locale>en</ns2:locale><ns2:userFirstName>Cinnamon</ns2:userFirstName><ns2:userId>CinnamonCookie</ns2:userId><ns2:userLastName>Cookie</ns2:userLastName></requestingUser></ns2:asyncCreateInstance></S:Body></S:Envelope>--------------------

**Comment by SylviaDehn** [comment]
The log file message is destroyed in the comment, but the value "mypassword" is seen in clear text

**Comment by SylviaDehn** [comment]
The reason for this may be error https://github.com/servicecatalog/development/issues/445

**Comment by StavrevaS** [comment]
Yes, the reason is issue #445. The passwords are not encrypted on SOAP API. The communication by SOAP API is always https, so it is not a problem. But the operator can see the passwords with the SOAP traces in the server.log. The password is saved encrypted, but it must be decrypted in order to be used for authentication for IaaS requests. So for the operator is anyway possible to get the password with using the key and the encryption algorithm. The encryption of the passwords is meant to secure the passwords from stealing the customer data by third party.
The issue is duplicate to #445.
