### ISSUE TITLE
The custom tab for the "My Subscriptions" page of AWS services

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/development#475]
Date:2016/12/02
[Steps to reproduce]
create a subscription with custom tab
go to My Subscription page
select a subscription
click customer tab
[Expected result]
looks fine for customer
as defined in cb

-
![mysubtab1](https://cloud.githubusercontent.com/assets/15209605/20831004/6dee1d4e-b883-11e6-8ec8-fb791f526aaa.PNG)

[Observed result]
![mysubtab2](https://cloud.githubusercontent.com/assets/15209605/20831008/71d1492c-b883-11e6-92f2-7c8970902aa7.PNG)

- layout unacceptable 
- name is missing
- access is missing

**Comment by elfriedegoetz** [comment]
The same for openstack
![mysubtab3](https://cloud.githubusercontent.com/assets/15209605/20887052/51ea30f6-baf9-11e6-88b9-4b21186d6812.PNG)

**Comment by redmond2683** [comment]
which version of oscm did you check this issue with?
i checked the issue with the current mater and the layout looks better. but regarding the "Name" column, implementation is missing.
![aws](https://cloud.githubusercontent.com/assets/14889311/20891684/cc178de4-bb0b-11e6-809a-241f3e4ce74c.png)

**Comment by redmond2683** [comment]
i found solution for displaying name. i will push my fix soon.
![aws2](https://cloud.githubusercontent.com/assets/14889311/20894919/94c96b1c-bb17-11e6-954d-474d1e43b058.png)

**Comment by redmond2683** [comment]
regarding the layout issue, i found the cause of the problem. enterprise packaging has not been adapted to this new styling which was added to the oscm-app-common library together with the custom tab feature, and so it overwrites the whole styling with an old one.

**Comment by redmond2683** [comment]
regarding the "Access information" problem, it is also caused by our enterprise packaging. the oscm-app.ear file is replaced with another ear file for enterprise version during packaging and the oscm-ear project, which is packaged into the oscm-app.ear file, was modified for implementing the custom tab feature. but the corresponding project for enterprise version has not yet been adapted. and so, the step which sets "Access information" is missing.
one more thing. the correct "Access information" is available in the Details tab. this is because "Access information" for the Details tab is obtained from the subscription table of the bss database, on the other hand the information for custom tab is obtained from the serviceinstance table of  the bssapp database, though it's lost en route for the reason which is mentioned above.

**Comment by redmond2683** [comment]
i fixed the problem with packaging

**Comment by elfriedegoetz** [comment]
Build 8.12.2016

test with aws-controller

now the layout is fine
access information will be displayed
Name will be displayed
click on MySubscription-> choose a sunscription-> click on the VM tab -> the application hangs
![tab1](https://cloud.githubusercontent.com/assets/15209605/21056001/0251e3fc-be34-11e6-9275-f2fbf3ed1c69.PNG)

**Comment by grubskim** [comment]
Cause of this issue:

The removal of the busy cursor is handled in onload event of the iframe.

The problem is caused because the content of the iframe can finish loading before the custom tab is clicked.

I have removed the busy cursor on tab headerclick event. It should not be needed as we have the loading message inside the tab anyway. 

Changes currently being testing on integration branch.

Bug branch: hotfix/issue-475-cursor-fix

**Comment by elfriedegoetz** [comment]
ok with BES_MASTER_UNIT-16952016/12/15
