### ISSUE TITLE
Windows spezific line endings in *.properties file(s)

### ISSUE THREAD

**Issue by mfalkenhahn** [servicecatalog/development#503]
`#` Copyright FUJITSU LIMITED 2016  \CR LF
`#` Configuration of Database Access. \CR LF
`#` This configuration is used for the initial setup and \CR LF
........

**Comment by GoebelL** [comment]
This is done intentionally and refers to concrete requirements. All properties files in OSCM - basically those which are meant to be edited by the user - have Windows line endings, in order to be complaint with all common text editors. Some text editors don't cope with LF only, which results in a content displaying as one a single line.

**Comment by mfalkenhahn** [comment]
But then this should be explicitly mentioned in the documentation.

**Comment by GoebelL** [comment]
@gertipoppel 
Don't we have this information in the manuals? If not, could you please add it.

**Comment by GoebelL** [comment]
The line endings of configuration files are not explicitly described in manuals. Unless we evidently face trouble with the present solution there is no need for documentation.
