### ISSUE TITLE
Incorrect layout after registration on marketplace

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/development#579]
1.       Click register on marketplace in SAML mode
2.       OpenAM window is shown
3.       Enter user credentials and click login
4.       Registration form is shown
5.       Enter all necessary data (User id is unchangeable)
6.       Click Register

![capture](https://cloud.githubusercontent.com/assets/18006407/23067307/f89f5eee-f51e-11e6-8759-fabcbba9502f.PNG)

**Comment by StavrevaS** [comment]
From Installation.pdf for SAML_SP mode:
"Customer self-registration is not supported in this case, and should thus be disabled".

This is not a valid scenario, since it is documented that the self-registration on the marketplace should be disabled in SAML_SP mode.
If enhancement request is necessary, should be created first and linked to this issue.
