### ISSUE TITLE
Parameter pricing preview calculator

### ISSUE THREAD

**Issue by maik-kulbe** [servicecatalog/development#614]
As a customer, I want to see a preview of how much a service configuration will cost, before booking a service.
 
The GUI should show a preview cost estimation of the current configuration of the service. This price information should be updated when the configuration changes.

**Comment by GoebelL** [comment]
Hi @maik-kulbe 

that's a nice feature with the pricing preview. Thank you for your contribution. @StavrevaS has reviewed and merged it for testing now. We'll need to clear about some change included on the parameter tool  API and how to deal compatibility. After we got this solved and tested we'll schedule it for next milestone.

**Comment by mdehn** [comment]
Hi @GoebelL 
please proceed and plan it for one of the next milestones.

**Comment by GoebelL** [comment]
The feature will be included with OSCM 17.2.

**Comment by StavrevaS** [comment]
There are some issues to be fixed before the feature is merged into master. The service parameter prices (per user and per subscription) are added to the JavaScript API, but not the currency of the price model.
Since OSCM supports different currencies, this should be fixed.
I will create separate issue for this problem.

**Comment by GoebelL** [comment]
The prices preview is not used by existing configuration tools. Since this tool is provided as a sample, the issues should not block us from including it with the next OSCM release. We should state them with limitations in the respective readme file.
