### ISSUE TITLE
build-db.xml has the references to jar that does not exist

### ISSUE THREAD

**Issue by toshihiro-shiino** [servicecatalog/development#697]
I download https://github.com/servicecatalog/development/releases/download/v17.0.0/oscm-install-pack.zip and extract it.
I find the line of "\<pathelement location="lib/oscm-app.jar" />" in oscm-install-pack\install\build-db.xml, but I can't find this jar in oscm-install-pack\install\lib.
Because of this line, I get the message of "dropping F:\Fujitsu\FSCTMG\setup\BESSetup\install\lib\oscm-app.jar from path as it doesn't exist" in build-db-ant.log.

**Comment by GoebelL** [comment]
Hi @toshihiro-shiino  
sorry, which jar are you referring to? 
>"I find the line of "" in oscm-install-pack\install\build-db.xml, but I can't find this jar"
For first check, I don't see any foreign or mistaken reference in build-db.xml.
oscm-app.jar is not part of oscm-install-pack. It's packaged within oscm-app.ear in oscm-app-install-pack.zip and all controller specific install packages.

**Comment by toshihiro-shiino** [comment]
sorry, I insert "\" for escaping.

**Comment by toshihiro-shiino** [comment]
oscm-app.jar is not part of oscm-install-pack, but oscm-install-pack currently refer to oscm-app.jar as a part of classpath.
I think it is a mistake.

**Comment by toshihiro-shiino** [comment]
@GoebelL Is it still uncleared?

**Comment by GoebelL** [comment]
@toshihiro-shiino
Thanks for enhancing the information. The issue is clear now. I confirm the oscm-app.jar is misplaced in "oscm-install-pack\install\build-db.xml". 
However, there are two build-db.xml files in OSCM core. Obviously I picked the  [wrong one](https://github.com/servicecatalog/development/blob/master/oscm-devruntime/javares/build-db.xml ) - therefore I was confused.
