### ISSUE TITLE
Different look table APP Platform Setting on GL3 and GL4

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/development#713]
Build: PRIVATE-BUILD-ON-ESTESSBESCIJS1 2017/05/16 
Windows Server 2016
jdk1.8u121
SAML mode
Glassfish 4

[How to reproduce]
Go to `http://<server>:<port>/oscm-app/`

[Expected result]
The APP Platform Setting looks as on Glassfish 3
![gl3](https://cloud.githubusercontent.com/assets/18006407/26304774/ec75139e-3eec-11e7-890a-3eb1577eb5da.PNG)

[Observed result]
The APP Platform on Glassfish 4 looks different:
![gl4](https://cloud.githubusercontent.com/assets/18006407/26304831/18cb2546-3eed-11e7-9fe9-9ee4a7b28b0b.PNG)

[Details]
The structure of the table on GL3 is:
`<table` id="appSettings:j_idt65" class="rf-dt `table_row_linetitle_class"`
`<colgroup` span="2"></colgroup>
`<thead` id="appSettings:j_idt65:th" class="rf-dt-thd">
`<tbody` id="appSettings:j_idt65:tb" class="rf-dt-b">
`<tbody` id="appSettings:j_idt65:sc">
`</table>`

but on GL 4 is unnecessary tag `<tfoot>`
`<table` id="appSettings:j_idt65" class="rf-dt table_row_linetitle_class">
`<colgroup` span="2"></colgroup>
`<thead` id="appSettings:j_idt65:th" class="rf-dt-thd">
`<tfoot` id="appSettings:j_idt65:tf" class="rf-dt-tft">
`<tbody` id="appSettings:j_idt65:tb" class="rf-dt-b">
`<tbody` id="appSettings:j_idt65:sc">
`</table>`

**Comment by kwodzynski** [comment]
#677

**Comment by GoebelL** [comment]
Hi @kwodzynski, 
you are right, this default branded admin UI style isn't that fancy. However, I don't see much difference in your both screenshots, except for that the GF4' one has this footer space and wider Setting key column. Since we got an JSF upgrade with shift to GF4 and some UI tweaking here and there, it's not necessarily unexpected or defect to result in a different appearance. 
Both styles are improvable. E.g. in both cases the input field widths are same short. Since the white label styling is not responsive to resizing, the solution here could be to create and deploy a nice overlay branding, which on-demand dynamically resizes the controls in a user-friendly fashion. Could be a cool feature. 

For here, let's check if it's quick and save to drop the mentioned table footer. If yes we go for it, if not we'll leave it.

**Comment by kwodzynski** [comment]
Hi @GoebelL,
The different width of Setting key column is caused by different size of browser in the screenshot moment. When I open both (gl3 and gl4) browsers on the same monitor, the width is the same as well.

**Comment by digitalfishpond** [comment]
Actually, it seems that that footer should be populated with {platformConfigurationCtrl.model.items[key]} (see settingsEditor.xhtml)
I propose a fix that only renders this footer when platformConfigurationCtrl.model.items is not empty by adding in settingsEditor.xhtml in newControllerId the attribute:
rendered="#{not empty platformConfigurationCtrl.model.items}"
I would also add the entire footer to the GF3 master so that it renders there too when the list is not empty.
Thoughts? Any objections?

**Comment by StavrevaS** [comment]
We will merge gf3 master to gf4 master soon. So if the gf4 is OK, then you can close this.

**Comment by kwodzynski** [comment]
Tested on Windows Server 2016, jdk1.8u121, build BES_MASTER_UNIT-1778 2017/06/29 (Official 17.2.0) in Saml mode. The table looks good.
