### ISSUE TITLE
Access control is missing by the SOAP method for updating the number of VM

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#716]
The new web method SubscriptionService.notifySubscriptionAboutVmsNumber() has no access control, which is not acceptable for a public API.

The following should be checked:
- role technology manager is needed;
- the technology manager must belong to the technology provider organization which is the owner of the subscribed service.

**Comment by SylviaDehn** [comment]
@StavrevaS are you sure that this shouldn't be fixed for 17.1?

**Comment by badziakp** [comment]
1st is fine.
Why it has to be true:

> the technology manager must belong to the technology provider organization which is the owner of the subscribed service.

?

**Comment by GoebelL** [comment]
Since it's public API it could be otherwise called just by any other technology manager in OSCM not owning the service.

**Comment by GoebelL** [comment]
@DawidCh, @badziakp  
Please this check again.

@StavrevaS wrote above:
"the technology manager must belong to the technology provider organization which is the owner of the subscribed service."

The modification in SubscriptionServiceBean, line 5583 doesn't seem to fulfill this request. "subscription.getOwner().getOrganization().getKey() != user.getOrganization().getKey()"
It checks the owner of the subscription instead of the technology provider of the underlying service.

I guess #759 and #755 are subsequent issues. Please check.

**Comment by GoebelL** [comment]
Should be something like:
Organization provider = user.getOrganization();
PermissionCheck.owns(subscription.getProduct().getTechnicalProduct(), provider, LOG, null);

**Comment by badziakp** [comment]
The problem was caused by the wrong check of user permissions. There was checking if a subscription owner has privileges to update subscription, now there is checked if the technology provider of the underlying service has such privileges.

**Comment by kwodzynski** [comment]
Checked on Windows Server 2016, jdk1.8u121, build BES_MASTER_UNIT-1773 2017/06/14 in SAML mode.
I have not noticed any problems.
