### ISSUE TITLE
Request for configuration of Marketplace ID freely from Web UI

### ISSUE THREAD

**Issue by toshihiro-shiino** [servicecatalog/development#742]
CTMG often assigns numbers for ID by expressing 32-bit random numbers in hex. Among various IDs, Marketplace ID is characteristically visible since it can be observed by all end-users by appearing in the mail sent when a user is created. As a result, we have been requested by customers to change this ID into something meaningful and human-readable and realized such requirement by directly updating bes database.
We request for a feature to freely configure Marketplace ID from Web UI since with future CTMGaaS in mind, we assume bes database access will be no longer allowed to Platform Operator.

**Comment by GoebelL** [comment]
The marketplace ID is internally given when the marketplace is created. This hex string refers to the ID of the initial owner organization. It is fix per axiom and cannot be made changeable. The ID serves as  business key in the marketplace domain model. Services from all tiers, web profile, session caches and cookies rely on it's constant value. 

@toshihiro-shiino 
Please check if this feature request would be covered as follows: 
"Extend the create marketplace dialog in the operator menu of the administration portal, in order to allow the platform operator for specifying the ID with marketplace creation without subsequent change option."

**Comment by toshihiro-shiino** [comment]
@GoebelL 
Your proposal meets our request.
thanks.

**Comment by toshihiro-shiino** [comment]
I'm sorry.
There was something I forgot to say.
We also create a marketplace with Platform API.
So it is necessary to enhance the API so that we can create a marketplace with the specified ID.

**Comment by grubskim** [comment]
@toshihiro-shiino 

> We also create a marketplace with Platform API.
Can you advise which API do you mean? SOAP, REST, command line, or web UI?

**Comment by toshihiro-shiino** [comment]
That means SOAP.
I think CTMG's Platform API is provided only with SOAP, is not it?
(I believe only a part related to the Notification API is also provided REST.

**Comment by toshihiro-shiino** [comment]
We've just confirmed that the implemented function works as expected.
Thank you, OSCM team!
