### ISSUE TITLE
LICENSE.txt file missing in licenses directory of oscm-install-pack

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#824]
[Build] 17.3+ 2017/08/30

[Expected result]
licenses/LICENSE.txt exists in oscm-install-pack.zip

[Observed result]
file is missing

**Comment by SylviaDehn** [comment]
just found this https://github.com/servicecatalog/development/pull/817

**Comment by SylviaDehn** [comment]
also this: https://github.com/servicecatalog/development/pull/818

**Comment by DawidCh** [comment]
Fixed by modification of packaging files.

**Comment by SylviaDehn** [comment]
[Build] 2017/09/04 reopen, file still missing

**Comment by SylviaDehn** [comment]
please also check controllers, file is missing here too

**Comment by badziakp** [comment]
Enterprise version fixed.

**Comment by SylviaDehn** [comment]
[Build] 17.4 
reopen because ".txt" extension is missing for LICENSE

**Comment by DawidCh** [comment]
Since the commits you mentioned in the comments https://github.com/servicecatalog/development/issues/824#issuecomment-325973565 and https://github.com/servicecatalog/development/issues/824#issuecomment-325973347 the license.txt file will never be present. It has been renamed to license. It is intentional rename so closing.
