### ISSUE TITLE
Provide sample data with initial setup

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#856]
* Supplier organization with technical user for IaaS controllers in APP (user roles: technology manager and supplier)
* OpenStack technical Service + Heat Template
* Marketplace
* Branding
* ....

**Comment by shimizuf** [comment]
The idea is:
* On database initialization it should be possible to add this sample data if desired

Thus the technical tasks would be:
* Create SQL files which provide only the sample data on top of a newly initialized databases
* Enhance oscm-initdb so that if the database is initialized from scratch, additionally the SQL files are imported if a switch is set, otherwise the clean database is left as is

Before that we must define:
* What exactly should the sample data be (which organizations, users, roles, services, marketplaces, etc.)?
* How many sets of sample data will we offer? One set or several?

**Comment by GoebelL** [comment]
One set shall be fine for now. But it would be good to keep it exchangeable when enhancing oscm-initdb.
