### ISSUE TITLE
Error while doing the modify operation using CTMG SOAP API

### ISSUE THREAD

**Issue by pujarisat** [servicecatalog/development#881]
Hi Team,

We are trying to call the the CTMG SOAP API and we are able to call below operation sucessfullu however we are facing below error while doing the modify operation.
1) create subscription 
2) start/stop opration
3) terminate subscription  
4) modify subscription  : getting below error 

Error : 2017-10-30 06:09:06,825 ERROR [Thread-9] unknown.jul.logger : org.oscm.types.exceptions.ConcurrentModificationException: EXCEPTIONID 1509343746754: EXCEPTIONID 1509343746754: Outdated VOParameter in version 0  

could you please proved same code for modify the operation

-Thanks and Regards
Satling Pujari

**Comment by GoebelL** [comment]
Hi @pujarisat 

The SOAP interface provides for modifying subscription parameters via `SubscriptionService#modifySubscription`.  Note that this method checks for concurrent modifications. It is expected to fail if parameters are modified, in order to avoid concurrent clients overwriting each other.  
In particular it expects correct versions of existing parameters. This means each `VOParameter` passed with `modifySubscription ` is required to contain a valid key and version >0, where key and version match the respective currently existing subscription parameter in the database. This condition is true if parameters are freshly read from database before calling modify and no concurrent modification has taken place in between.

The modifySubscription checks the given subscription parameters and [fires a ConcurrentModificationException](https://github.com/servicecatalog/development/blob/master/oscm-subscriptionmgmt/javasrc/org/oscm/subscriptionservice/bean/SubscriptionServiceBean.java#L3827) in case given versions do not match the existing versions.

[How to solve]
Try refreshing the parameter data before calling modify. Use `SubscriptionService#getSubscriptionDetails` to obtain the subscription data.
