### ISSUE TITLE
OSCM multi tenancy issue with SOAP API

### ISSUE THREAD

**Issue by DashThink** [servicecatalog/development#885]
Hi,

We have CTMG environment  ( Multi-tenanat -17.4 ) with AD1(Default) and AD2. We have created Orgs, marketplaces , Users and deployed marketable services on both the ADs ( connected org and marketplaces respectively ).
When we try to create subscription through UI and API it works fine for the default AD1 marketable service. Also when we try to create subscription on AD2 marketable service it works fine for the UI. But when we try to create subscription of AD2 through the API it gives us the below error... Please suggest the solution..

2017-12-07 12:06:07,085 ERROR [Thread-9] unknown.jul.logger : javax.xml.ws.soap.SOAPFaultException: ID3242: The security token could not be authenticated or authorized.
	at com.sun.xml.ws.security.trust.impl.wssx.WSTrustElementFactoryImpl.checkElement(WSTrustElementFactoryImpl.java:913)
	at com.sun.xml.ws.security.trust.impl.wssx.WSTrustElementFactoryImpl.createRSTRCollectionFrom(WSTrustElementFactoryImpl.java:495)
	at com.sun.xml.ws.security.trust.impl.TrustPluginImpl.parseRSTR(TrustPluginImpl.java:752)
	at com.sun.xml.ws.security.trust.impl.TrustPluginImpl.invokeRST(TrustPluginImpl.java:631)
	at com.sun.xml.ws.security.trust.impl.TrustPluginImpl.process(TrustPluginImpl.java:175)
	at com.sun.xml.ws.security.trust.impl.client.STSIssuedTokenProviderImpl.getIssuedTokenContext(STSIssuedTokenProviderImpl.java:144)
	at com.sun.xml.ws.security.trust.impl.client.STSIssuedTokenProviderImpl.issue(STSIssuedTokenProviderImpl.java:74)
	at com.sun.xml.ws.api.security.trust.client.IssuedTokenManager.getIssuedToken(IssuedTokenManager.java:83)
	at com.sun.xml.wss.jaxws.impl.SecurityClientTube.invokeTrustPlugin(SecurityClientTube.java:686)
	at com.sun.xml.wss.jaxws.impl.SecurityClientTube.processClientRequestPacket(SecurityClientTube.java:283)
	at com.sun.xml.wss.jaxws.impl.SecurityClientTube.processRequest(SecurityClientTube.java:249)

**Comment by pujarisat** [comment]
Hi Team,

Do you have any update on this ?

-Thanks & Regards,
Satling Pujari

**Comment by toshihiro-shiino** [comment]
1. Has the signing public key of AD 2 registered in CTMG?
2. Is WSDL endpoint valid? It is different between default case and other tenants.

**Comment by toshihiro-shiino** [comment]
@pujarisat @DashThink 
Do you have any comment?

**Comment by StavrevaS** [comment]
I assume that the stack trace is from the catalog manager domain.  The error message says that CTMG receives a token from the ADFS, which could not be authenticated or authorized.
"2017-12-07 12:06:07,085 ERROR [Thread-9] unknown.jul.logger : javax.xml.ws.soap.SOAPFaultException: ID3242: The security token could not be authenticated or authorized."

It may be something wrong with installed certificates. Please check.
Since the ADFS uses X509 certificates to sign all tokens that it issues.  More details about configuring ADFS regarding certificates:
https://blogs.technet.microsoft.com/askpfeplat/2015/01/26/adfs-deep-dive-certificate-planning/

We have a scenario with 3 parties, CTMG, Service Client and IDP (ADFS). Regarding ceritficates, the setup should be as following:
- The CTMG imports the token-signing certificate (public part) from ADFS in its domain trusstore;
- The Service Client imports the communication certificate (ssl) from ADFS and from CTMG domain (usually s1as);
- The Relying Party in ADFS have possibility for specifying "Encryption" and "Signature" certificates. These are CTMG public certs.  "Encryption" should contain a public cert from CTMG if we want the token to be encrypted and "Signature" is for verifying signed authentication requests from the CTMG.


The tenantID is not included in the token verification in Metro, it is verified from the CTMG, so this problem is not related to multi-tenancy, but probably it is a configuration issue.

**Comment by c-yan** [comment]
> so this problem is not related to multi-tenancy
No.
> but probably it is a configuration issue.
But it is yes.

Because they are using WSDL URL that do not contain tenant ID, they are accessing the IDP of the default tenant with ID / PW of non default tenant.
So, of course, they are getting authentication error.

**Comment by toshihiro-shiino** [comment]
> so this problem is not related to multi-tenancy

No.

> but probably it is a configuration issue.

But it is yes.

Because they are using WSDL URL that do not contain tenant ID, they are accessing the IDP of the default tenant with ID / PW of non default tenant.
So, of course, they are getting authentication error.

**Comment by toshihiro-shiino** [comment]
> The Service Client imports the communication certificate (ssl) from ADFS and from CTMG domain (usually s1as);

I think that it is necessary only when the SSL certificate is self-signed.
Generally it is unnecessary.

**Comment by toshihiro-shiino** [comment]
@StavrevaS 
Do you have information on how to write wsit-client.xml when calling API between multiple tenant on one application?

**Comment by StavrevaS** [comment]
@toshihiro-shiino 
here is an example how to have a wsit-client.xml for multiple IDPs. You only add the wsdl files for the STS services for each IDP. In our example we have ADFS and some mock STS service:

<?xml version="1.0" encoding="UTF-8"?>
<definitions
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  name="mainclientconfig">
  <import
    location="ShortADFS_STS_Service.xml"
    namespace="http://schemas.microsoft.com/ws/2008/06/identity/securitytokenservice"/>
  <import
    location="STSService.xml"
    namespace="http://sts.mocksts.oscm.org/Imports" />
</definitions>

**Comment by toshihiro-shiino** [comment]
@StavrevaS
Does this example work even if multiple IDPs are the same namespace?
Both the default tenant and the other tenant are the same namespace,  because all tenants are ADFS.
actual namespace is "http://schemas.microsoft.com/ws/2008/06/identity/securitytokenservice".

**Comment by StavrevaS** [comment]
I would say there should be no problems with same namespaces.  The namespace is used for the internal referencing in the XML document to make sure it is valid as declared from the schema.

**Comment by toshihiro-shiino** [comment]
@StavrevaS
OK, I understand.
Thanks.

**Comment by pujarisat** [comment]
Hi Team,

We have able to call CTMG SOAP API using customer AD and same has been tested , working fine.

Thanks for valuable support /Help

-Thanks ,
Satling

**Comment by GoebelL** [comment]
@pujarisat 
Thank you for confirming this.
