### ISSUE TITLE
Rollback parameters

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#892]
_From @StavrevaS on January 18, 2018 11:10_

In the org.oscm.app.domain.ServiceInstance class there is a parameter rollback logic.
I suspect that there is a problem there because of improper method usage.

Please check the method 

```
  private void rollbackInstanceParameters(
            Properties rollbackInstanceParameters, EntityManager em)
            throws BadResultException {

        HashMap<String, Setting> rollbackParams = new HashMap<>();

        for (String name : rollbackInstanceParameters.stringPropertyNames()) {
            rollbackParams.put(name, new Setting(name,
                    rollbackInstanceParameters.getProperty(name)));
        }
        this.removeParams(rollbackParams, em);
        this.setInstanceParameters(rollbackParams);
        this.setRollbackParameters(null);

    }

```

After introducing the rollback of attributes the values in the properties are not strings anymore, but objects of type Setting. The method rollbackInstanceParameters.stringPropertyNames() returns only the properties keys if the key AND value are of type String. So I would expect here that we always get empty set.

The same is valid for rollbackInstanceAttributes method.

_Copied from original issue: servicecatalog/oscm-app#4_

**Comment by StavrevaS** [comment]
It seems that the Java Properties.storeToXML() used to serialize the properties to XML for rollback, is working only for String keys and values. The properties with object values are ignored.
To fix this new JSON or XML serializer is needed, so the new format will not be compatible with the existing XML.
This should not be a problem if the redeployment of the fixed APP is done when all service instances are in COMPLETED state. The new serialized value prepared by modify request will overwrite the existing one.

**Comment by StavrevaS** [comment]
The problem is solved with conversions methods between the map and properties, so that the map values which are objects are represented with 3 property entries. For example if the object in the map is parameter setting with name "instance_image", value "image123" and encryption flag set to false, in the properties it would be represented with 3 entries:
param1.name=instance_image
param1.value=image123
param1.encryption=false
Example for the next parameter in the map:
param2.name=disk_size
param2.value=100GB
param2.encryption=false
.....

The problems with the java XML serialization of properties,  described in the previous comments will not exist anymore.

The same methods are used for the instance attributes (UDAs), only the property key prefix is "att".
att1.name=...
att1.value=...
att1.encryption=...
...

**Comment by SylviaDehn** [comment]
[Build] 17.3.1 verified
