### ISSUE TITLE
Hotfix  17.3.1 subscription issue.

### ISSUE THREAD

**Issue by pujarisat** [servicecatalog/development#909]
Hi Team

As soon as we subscribe any service we are getting below attached error.But in the controller it creates instance at the v Center side and subscription goes into pending state.

Please find the attached server log and controller logs also attached error message on screen

 
[app-vmware.log](https://github.com/servicecatalog/development/files/1676775/app-vmware.log)
![errorimage](https://user-images.githubusercontent.com/22190140/35554727-b6e977e0-05c2-11e8-8c29-c313a104f495.png)
[server.log](https://github.com/servicecatalog/development/files/1676776/server.log)

**Comment by GoebelL** [comment]
The attached trace points to a NPE thrown in the custom VMWare adapter.
Caused by: java.lang.NullPointerException
	at com.fujitsu.bss.app.vmware.controller.PropertyHandler.getCount(PropertyHandler.java:252)
	at com.fujitsu.bss.app.vmware.controller.Dispatcher.dispatch(Dispatcher.java:138)
	at com.fujitsu.bss.app.vmware.controller.VmwareController.getInstanceStatus(VmwareController.java:295)

Please check your implementation around PropertyHandler.getCount.

As by change in 17.3.1, OSCM displays an error message in case of a provisioning error, which includes a reason message as returned by the controller. The subscription is left in PENDING in this case.

**Comment by pujarisat** [comment]
Hi Team,

Thanks for your valuable support and help.

-Thanks and Regards
Satling
