### ISSUE TITLE
HeadersTest is still checking the last year 2017 for copy right in headers

### ISSUE THREAD

**Issue by xusuest** [servicecatalog/development#919]
The following test should be corrected so that the current year for copy right in headers will be checked.
development/oscm-common-unittests/javasrc/org/oscm/headers/HeadersTest.java

All the files containing "Copyright FUJITSU LIMITED 2017" should be corrected with "Copyright FUJITSU LIMITED 2018".

**Comment by GoebelL** [comment]
The purpose of this test is to ensure the required copyright headers in all contributions according Contributor License Agreements (ICLA+CCLA) of OSCM. The exact year is not significant here. To avoid maintenance overhead this should be removed from the check. 
Fixed with https://github.com/servicecatalog/development/pull/922
