### ISSUE TITLE
Custom attributes handling not consistent

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/development#93]
Task 1:

Add indexing to the UdaDefinition defaultvalue.

Task 2 (done, but review again):

Lucene Search Uda values, should result in a set of subscription keys.

1. Ignore the values of Udas with configurationtype "SUPPLIER" in the UdaDefinition. (done).
2. Udas with targettype "CUSTOMER_SUBSCRIPTION" in the definition: add targetobjectkey (uda subscription key) to the result keys. (done)
3. Udas with targettype "CUSTOMER" in the definition: 
add all subscriptions of a logged in customer (uda targetobjectkey) and product vendor is the supplier which owns the udas (organizationkey from UdaDefinition). (done)

Task 3:

Lucene Search UdaDefinition default values.

1. Ignore the values of UdaDefinition with configurationtype "SUPPLIER".

2. UdaDefinitions with targettype "CUSTOMER_SUBSCRIPTION": add  subscriptions of the logged in customer where product vendor is supplier which owns the UdaDefinition (organizationkey) and there are no uda values for these subscriptions.

3. UdaDefinitions with targettype "CUSTOMER": 
ignore those uda definitions

**Comment by StavrevaS** [comment]
UdaDefinition indexing is not complete. The initial indexing is missing (see how Uda table is initially indexed).

The query for searching the subscriptions with default subscription uda values does not work properly. Please fix and add unit tests.

**Comment by badziakp** [comment]
I tested following cases:

1. log in as supplier and create customer
2. go to Account -> Manage custom attributes
3. add two attributes for subscriptions: UDA1 with default value: portal, UDA2 with no default value
4. go to marketplace and log in as customer
5. create subscription sub1 with UDA1 = portal, UDA2 empty
6. create subscription sub2 with UDA1 = catalog, UDA2 empty
7. create subscription sub3 with UDA1 empty, UD2 = manager
8. create subscription sub4 with UDA1 empty, UD2 empty
9. create subscription sub5 with UDA1 manager, UD2 application
10. create subscription sub6 with UDA1 portal, UD2 application

(wait for indexing to be done. On my environment it takes about 2 minutes)

10. go to Subscriptions page and enter: 
a) portal (sub1, sub3, sub4, sub6)
b) catalog (sub2)
c) manager (sub3, sub5)
d) application (sub5, sub6)

All of these cases work ok.
I can't reproduce any error case related custom attributes. 

@StavrevaS 
Could you tell me if there is anything else to be done in this issue?

**Comment by StavrevaS** [comment]
Your test scenario is maybe too simple. Create more organizations or at least two (suppliers and customers). Customers have subscription from different suppliers, suppliers have also subscriptions.

**Comment by badziakp** [comment]
The following case was fixed:
1.  login as supplier and create marketable service
2. go to marketplace and subscribe
3. go to portal annd add custom attribute with default value concerning subscription
4. go to marketplace -> Account -> Subscriptions and try to search by custom attribute default value

[Expected result]
The created subscription should be find

**Comment by jiangweiyi** [comment]
I test following case, there are still some problems, so I think it should be reopened:

1. Platform operator create 2 suppliers, 1 marketplace and 1 customer: sp1, sp2, mk, cu;
2. Do not define custom attribute for subscriptions now;
3. Sp1 publish a service sv1 on marketplace mk, sp2 publish a service sv2 on mk;
4. Customer cu go to mk, subscribe sv1 and sv2;
5. Sp1 define attributes for subscriptions x=xx, y=yy;
6. Sp2 define attributes for subscriptions a=aa, b=bb;
7. After about 5 minutes, cu go to mk, search with "xx", "yy", "aa", "bb" in subsciption page. 
8. Sp1 publish sv3 on mk, sp2 publish sv4 on mk;
9. Cu go to mk, subscribe sv3 and sv4 with the default value of all the attributes;
10. After about 5 minutes, search with "xx", "yy", "aa", "bb" in subscription page.

[Observed result]
After step7, sv1 and sv2 can be searched out with all attributes "xx", "yy", "aa", "bb";
After step10, sv1, sv2, sv3, sv4 can be searched out with all attributes "xx", "yy", "aa", "bb";

[Expected result]
After step7, since during subscribe sv1 and sv2, no need to input the attributes, I think they cannot be searched out by input "xx" "yy" "aa" "bb";
After step10, "xx" or "yy" should only search out sv3, "aa" or "bb" should only search out sv4;

**Comment by SylviaDehn** [comment]
I disagree with the above, we are clarifying, and will add comments in a bit.

**Comment by SylviaDehn** [comment]
[Build] 2016/08/04 Custom attributes did not take into account more than one supplier.

**Comment by MiethanerR** [comment]
fixed together with issue #117

**Comment by SylviaDehn** [comment]
[Build]2016/08/09 verified
